import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ubuntu.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col prose lg:prose-xl max-w-none">
        <nav className="container flex items-center justify-between mx-auto">
          <h2>ReadBlog</h2>
          <ul className="flex gap-2 items-center">
            <Link href="/">Articles</Link>
            <Link href="/create">Create Article</Link>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
