import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Ubuntu } from "next/font/google";
import { AuthProvider } from "@/lib/authContext";
import { Navbar } from "@/components/Navbar";

const ubuntu = Ubuntu({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ubuntu",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ubuntu.variable} h-full antialiased`}>
      <AuthProvider>
        <body className="min-h-full flex flex-col prose lg:prose-xl max-w-none">
          <Navbar />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
